docs/config.md
docs/contributing.md
src/checks.rs
src/cli.rs
src/main.rs

add `-t` flag to pre-command to run the checks in dry-run for easy debugging new checks

add pre-command dry-run

---

shellfirm.plugin.zsh

add zsh plugin file

---

src/config.yaml

fix rm regex

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/support_more_checks.md

adding issue templates

---

checks/fs.yaml

adding 2 new risky commands to fs group
1. Detect chmod 777 / 
2. Detect find -delete which going to delete all the files under your current path

adding 'chmod 777 /' and 'find -delete' to check detector

---

checks/fs.yaml

Improve FS checks.
* change rm -rf regex
* change chmod -R 777

improve fs checks

---

README.md
checks/base.yaml
checks/fs.yaml
checks/git.yaml
checks/kubernetes.yaml
docs/config.md
src/checks.rs
src/config.rs

change `is` to `test` for better text explanation

change config field from 'is' to 'test'

---

.github/workflows/ci.yaml

Skip GitHub action on `*.md` or `docs` folder or just push the branch

ignore *.md files + doc folder

---

README.md
docs/checks.md
docs/checks/base.md
docs/checks/fs.md
docs/checks/git.md
docs/checks/kubernetes.md

adding checks explanations

---

README.md
checks/fs-strict.yaml
docs/checks/fs-strict.md

Adding new file system check when user want to be more strict with the commands

adding fs-strict checks

---

src/main.rs

adding a better message when config file is invalid

adding better error when config file is invalid

---

README.md
src/checks.rs
src/config.rs

add the option to control different challenge per check

---

Cargo.lock
Cargo.toml

bump version 0.1.3

---

checks/fs-strict.yaml
checks/fs.yaml
docs/checks/fs.md
src/main.rs

improve rm pattern

---

checks/fs-strict.yaml
checks/fs.yaml
src/checks.rs

improve chmod pattern

---

README.md
docs/installation/bash.md
shellfirm.plugin.sh

Add pre-exec hook in bash

---

checks/base.yaml

add reboot and shutdown patterns

add reboot and shutdown patterns

---

src/checks.rs

replace `~` to home dir path in file exists filter

change ~ to home dir in IsFileExists FILTER

---

README.md
checks/heroku.yaml
docs/checks/heroku.md

add heroku risky patterns

---

docs/checks/fs.md

I've tried to clarify the descriptions of the checks a little, since I found some of them misleading, and improve the grammar (although mine is not perfect either!).

docs/checks/fs - clarify descriptions

---

docs/installation/fishshell.md

Just a minor change in the title.

Change title for fish installation instructions (fix typo)

---

Cargo.lock
shellfirm/Cargo.toml
shellfirm/src/config.rs
shellfirm/src/snapshots/shellfirm__config__test_config__can_backup-2.snap
shellfirm/src/snapshots/shellfirm__config__test_config__can_backup.snap

interactive menu in config reset command

---

shellfirm/src/checks.rs
shellfirm/src/snapshots/shellfirm__checks__test_checks__can_check_custom_filter-2.snap
shellfirm/src/snapshots/shellfirm__checks__test_checks__can_check_custom_filter.snap
shellfirm/src/snapshots/shellfirm__checks__test_checks__can_check_is_contains-2.snap
shellfirm/src/snapshots/shellfirm__checks__test_checks__can_check_is_contains.snap
shellfirm/src/snapshots/shellfirm__checks__test_checks__can_check_is_regex_match-2.snap
shellfirm/src/snapshots/shellfirm__checks__test_checks__can_check_is_regex_match.snap
shellfirm/src/snapshots/shellfirm__checks__test_checks__can_check_is_start_with-2.snap
shellfirm/src/snapshots/shellfirm__checks__test_checks__can_check_is_start_with.snap
shellfirm/src/snapshots/shellfirm__checks__test_checks__can_is_match_contains-2.snap
shellfirm/src/snapshots/shellfirm__checks__test_checks__can_is_match_contains.snap
shellfirm/src/snapshots/shellfirm__checks__test_checks__can_is_match_start_with-2.snap
shellfirm/src/snapshots/shellfirm__checks__test_checks__can_is_match_start_with.snap
shellfirm/src/snapshots/shellfirm__checks__test_checks__can_run_check_on_command-2.snap
shellfirm/src/snapshots/shellfirm__checks__test_checks__can_run_check_on_command.snap

check test

---

.github/workflows/ci.yaml
.github/workflows/release.yml
Makefile

Will need to modify the formula here after
https://github.com/kaplanelad/homebrew-tap/blob/main/shellfirm.rb

add Native support for Apple silicon

---

Cargo.lock
shellfirm/Cargo.toml

add Native support for Apple silicon #126. thanks @vmule

bump version 0.2.7

---

Cargo.lock
docs/checks/fs-strict.md
shellfirm/Cargo.toml
shellfirm/checks/fs-strict.yaml
shellfirm/tests/checks/fs-strict-folder_deletion.yaml
shellfirm/tests/snapshots/checks__fs-strict-folder_deletion.yaml.snap

[#128](https://github.com/kaplanelad/shellfirm/issues/128)

Added: Detect any folder deletion (`rmdir`) command.
